/* 
 * File:   hal_interrupt_gen_config.h
 * Author: Alielden
 *
 * Created on October 9, 2023, 7:05 PM
 */


#ifndef HAL_INTERRUPT_GEN_CONFIG_H
#include "../device_config.h"
#include "../mcal_std_types.h"



#define INTERRUPT_FEATURE_ENABLE 1

//#define INTERRUPT_PRIORITY_LEVELS_ENABLE  INTERRUPT_FEATURE_ENABLE
#define ADC_INTERRUPT_FEATURE_ENABLE        INTERRUPT_FEATURE_ENABLE
#define TIMER0_INTERRUPT_FEATURE_ENABLE     INTERRUPT_FEATURE_ENABLE
#define TIMER1_INTERRUPT_FEATURE_ENABLE     INTERRUPT_FEATURE_ENABLE
//#define TIMER2_INTERRUPT_FEATURE_ENABLE     INTERRUPT_FEATURE_ENABLE
#define TIMER3_INTERRUPT_FEATURE_ENABLE     INTERRUPT_FEATURE_ENABLE
#define CCP1_INTERRUPT_FEATURE_ENABLE       INTERRUPT_FEATURE_ENABLE
#define CCP2_INTERRUPT_FEATURE_ENABLE       INTERRUPT_FEATURE_ENABLE
#define USART_TX_INTERRUPT_FEATURE_ENABLE   INTERRUPT_FEATURE_ENABLE
#define USART_RX_INTERRUPT_FEATURE_ENABLE   INTERRUPT_FEATURE_ENABLE
//#define MSSP_I2C_INTERRUPT_FEATURE_ENABLE   INTERRUPT_FEATURE_ENABLE

#endif	/* HAL_INTERRUPT_GEN_CONFIG_H */

